inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0

Style/SpecialGlobalVars:
  Enabled: true
  Exclude: ["nicetest.gemspec"]
