name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.3'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run the default task
      run: bundle exec rake

    - name: Install gem
      run: bundle exec rake build && mv pkg/*.gem pkg/nicetest.gem

    - uses: actions/checkout@v4
      with:
        repository: Shopify/liquid
        ref: 77bc56a1c28a707c2b222559ffb0b7b1c5588928
        path: tmp/liquid

    - name: Run on another repo
      run: |
        gempath="$PWD/pkg/nicetest.gem"
        cd tmp/liquid
        bundle install --jobs 4 --retry 3
        gem install "$gempath" --no-document
        nicetest --reporter spec,junit

