name: Ruby

on:
  push:
    branches:
      - main
      - integration

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3", "3.4", "ruby-head"]
    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Test and build gem
      env:
        RUBYGEMS_FORCE_DISABLE_GEM_SIGNING: "true"
      run: |
        bundle exec rake
        bundle exec rake build
        mv pkg/*.gem pkg/nicetest.gem

    - uses: actions/checkout@v4
      with:
        repository: Shopify/liquid
        ref: 77bc56a1c28a707c2b222559ffb0b7b1c5588928
        path: tmp/liquid

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        working-directory: tmp/liquid

    - name: Run tests on another repository
      run: |
        gempath="$PWD/pkg/nicetest.gem"
        cd tmp/liquid
        gem install "$gempath" --no-document
        nicetest --reporter spec,junit
        nicetest test/unit/parser_unit_test.rb:15 test/unit/parser_unit_test.rb:38 > result.txt

        if grep -q "2 tests" result.txt; then
          echo "All tests passed"
        else
          echo "Some tests failed"
          cat result.txt
          exit 1
        fi

