name: Ruby

on:
  push:
    branches:
      - main
      - integration

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.3'

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Test and build gem
      run: |
        bundle exec rake
        bundle exec rake build
        mv pkg/*.gem pkg/nicetest.gem

    - uses: actions/checkout@v4
      with:
        repository: Shopify/liquid
        ref: 77bc56a1c28a707c2b222559ffb0b7b1c5588928
        path: tmp/liquid

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        working-directory: tmp/liquid

    - name: Run tests on another repository
      run: |
        gempath="$PWD/pkg/nicetest.gem"
        cd tmp/liquid
        gem install "$gempath" --no-document
        nicetest --reporter spec,junit

